[package]
name = "arkworks-threshold-decryption"
version = "0.0.1"
authors = ["ValarDragon <dev@sikka.tech>"]
edition = "2018"


[dependencies]
ark-ff = { git = "https://github.com/arkworks-rs/algebra", default-features = true }
ark-ec = { git = "https://github.com/arkworks-rs/algebra", default-features = true }
ark-std = { git = "https://github.com/arkworks-rs/utils", default-features = true }
ark-poly = { git = "https://github.com/arkworks-rs/algebra", default-features = false }

bls-crypto = { git = "https://github.com/sikkatech/celo-bls-snark-rs", branch="make_hashes_have_new_fn", default-features = false }

chacha20 = { version = "0.6.0" }
rand_core = { version = "0.5" }