name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rustlang/rust:nightly
    steps:
    - uses: actions/checkout@v2
    - name: Format
      run: cargo fmt
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
